language: node_js
sudo: required

branches:
  only:
    - master

cache:
  directories:
    - node_modules

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd web
  - ls
  - sudo docker build -t user_web .
  - cd ..
  - docker images
  - cd server
  - sudo docker build -t user_server .
  - cd ..
  - docker push grandpawang/user_web:laster
  - docker push grandpawang/user_server:laster